name: My First Workflow 
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "👏 hello world!"

      - name: Checkout 
        uses: actions/checkout@3.5.2

      - name: List files in the repositories 
        run: |  
          echo "The repository ${{ github.repository }} contains the following files"
          tree
